#!/bin/bash

# Definir o caminho do arquivo payload com base no diretório do Squid
if [ -d "/etc/squid/" ]; then
    payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
    payload="/etc/squid3/payload.txt"
else
    echo "Nenhum diretório Squid encontrado."
    exit 1
fi

# Exibir cabeçalho
tput setaf 7; tput setab 4; tput bold
printf '%35s%s%-10s\n' "Adicionar Host ao Squid Proxy"
tput sgr0

# Verificar se o arquivo payload existe
if [ ! -f "$payload" ]; then
    tput setaf 7; tput setab 4; tput bold
    echo ""; echo "Arquivo $payload não encontrado"; echo ""
    tput sgr0
    exit 1
else
    # Exibir os domínios atuais
    tput setaf 2; tput bold
    echo ""; echo "Domínios atuais no arquivo $payload:"
    tput sgr0
    tput setaf 3; tput bold
    echo ""; cat "$payload"; echo ""
    tput sgr0
    
    # Solicitar domínio ao usuário
    read -p "Digite o domínio que deseja adicionar à lista: " host
    
    # Verificar se o domínio foi inserido
    if [[ -z $host ]]; then
        tput setaf 7; tput setab 4; tput bold
        echo ""; echo "Você digitou um domínio vazio ou não existente!"; echo ""
        tput sgr0
        exit 1
    else
        # Verificar se o domínio já existe no arquivo
        if grep -q "^$host" "$payload"; then
            tput setaf 7; tput setab 4; tput bold
            echo ""; echo "O domínio $host já existe no arquivo $payload"; echo ""
            tput sgr0
            exit 1
        else
            # Verificar se o domínio inicia com ponto
            if [[ $host != \.* ]]; then
                tput setaf 7; tput setab 4; tput bold
                echo ""; echo "Você deve adicionar um domínio iniciando com um ponto!"
                echo "Por exemplo: .phreaker56.xyz"
                echo "Não é necessário adicionar subdomínios se o domínio principal já estiver na lista."
                echo ""; tput sgr0
                exit 1
            else
                # Adicionar domínio ao arquivo e remover linhas vazias
                echo "$host" >> "$payload"
                grep -v "^$" "$payload" > /tmp/a && mv /tmp/a "$payload"
                tput setaf 7; tput setab 1; tput bold
                echo ""; echo "Arquivo $payload atualizado. O domínio foi adicionado com sucesso:"; tput sgr0
                tput setaf 3; tput bold
                echo ""; cat "$payload"; echo ""
                tput sgr0
                
                # Recarregar o Squid
                if systemctl is-active --quiet squid; then
                    systemctl reload squid
                elif systemctl is-active --quiet squid3; then
                    systemctl reload squid3
                else
                    tput setaf 7; tput setab 4; tput bold
                    echo ""; echo "Nenhum serviço Squid em execução."; echo ""
                    tput sgr0
                fi

                # Mensagem de sucesso ao recarregar
                tput setaf 7; tput setab 1; tput bold
                echo ""; echo "O Proxy Squid foi recarregado com sucesso!"; echo ""
                tput sgr0
                exit 0
            fi
        fi
    fi
fi
