#!/bin/bash

# Função para exibir mensagens de erro
show_error() {
    tput setaf 7; tput setab 1; tput bold
    echo ""; echo "$1"; echo ""
    tput sgr0
    exit 1
}

# Função para exibir mensagens de sucesso
show_success() {
    tput setaf 7; tput setab 4; tput bold
    echo ""; echo "$1"; echo ""
    tput sgr0
}

# Exibir cabeçalho
tput setaf 7; tput setab 4; tput bold
printf '%35s%s%-10s\n' "Alterar Senha de Usuário"
tput sgr0
echo ""

# Exibir lista de usuários e suas senhas
echo -e "\033[1;33mLISTA DE USUARIOS E SUAS SENHAS: \033[0m"
echo ""

_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
i=0
unset _userPass

while read -r _user; do
    i=$((i + 1))
    _oP=$i
    [[ $i -lt 10 ]] && _oP="0$i"

    if [[ -e "/etc/SSHPlus/senha/$_user" ]]; then
        _senha=$(cat "/etc/SSHPlus/senha/$_user")
    else
        _senha='Null'
    fi
    
    suser=$(echo -e "\033[1;31m[\033[1;36m$_oP\033[1;31m] \033[1;37m- \033[1;32m$_user\033[0m")
    ssenha=$(echo -e "\033[1;33mSenha\033[1;37m: $_senha")
    printf '%-60s%s\n' "$suser" "$ssenha"
    _userPass+="\n${_oP}:${_user}"
done <<< "$_userT"

num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
echo ""

# Solicitar escolha do usuário
echo -ne "\033[1;32mDigite ou selecione um usuário \033[1;33m[\033[1;36m1\033[1;31m-\033[1;36m$num_user\033[1;33m]\033[1;37m: "
read -r option

user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)

# Validação da escolha
if [[ -z $option || -z $user ]]; then
    show_error "Campo vazio ou inválido!"
fi

# Verificar se o usuário existe no sistema
if getent passwd "$user" > /dev/null; then
    echo -ne "\n\033[1;32mNova senha para o usuário \033[1;33m$user\033[1;37m: "
    read -r password
    sizepass=${#password}

    # Validar se a senha tem pelo menos 4 caracteres
    if [[ $sizepass -lt 4 ]]; then
        show_error "Senha inválida! Use no mínimo 4 caracteres."
    fi

    # Verificar se o usuário está conectado
    if ! pgrep -u "$user" > /dev/null; then
        echo "$user:$password" | chpasswd
        show_success "A senha do usuário $user foi alterada para: $password"
        echo "$password" > "/etc/SSHPlus/senha/$user"
        exit 0
    else
        echo ""
        show_success "Usuário conectado. Desconectando..."
        pkill -f "$user"
        echo "$user:$password" | chpasswd
        show_success "A senha do usuário $user foi alterada para: $password"
        echo "$password" > "/etc/SSHPlus/senha/$user"
        exit 0
    fi
else
    show_error "O usuário $user não existe!"
fi
