#!/bin/bash
clear

# Função para reiniciar serviços
restart_services() {
    service ssh restart > /dev/null 2>&1
    service dropbear restart > /dev/null 2>&1
}

# Função para adicionar o banner
add_banner() {
    echo -ne "\033[1;32mQUAL MENSAGEM DESEJA EXIBIR\033[1;31m ?\033[1;37m : "; read msg1
    if [[ -z "$msg1" ]]; then
        echo -e "\n\033[1;31mCampo vazio ou inválido!\033[0m"
        sleep 2
        banner_menu
    fi

    # Escolher tamanho da fonte
    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m FONTE PEQUENA"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m FONTE MEDIA"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m FONTE GRANDE"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m FONTE GIGANTE"
    echo ""
    echo -ne "\033[1;32mQUAL O TAMANHO DA FONTE\033[1;31m ?\033[1;37m : "; read opc

    case $opc in
        1|01) _size='6' ;;
        2|02) _size='4' ;;
        3|03) _size='3' ;;
        4|04) _size='1' ;;
        *) 
            echo -e "\n\033[1;31mOpção inválida!\033[0m"
            sleep 2
            banner_menu
            ;;
    esac

    # Escolher cor da fonte
    echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m AZUL"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m VERDE"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m VERMELHO"
    echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m AMARELO"
    echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m ROSA"
    echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CYANO"
    echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m LARANJA"
    echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m ROXO"
    echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m PRETO"
    echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m SEM COR"
    echo ""
    echo -ne "\033[1;32mQUAL A COR\033[1;31m ?\033[1;37m : "; read ban_cor

    case $ban_cor in
        1|01) echo "<h$_size><font color='blue'>$msg1</font></h$_size>" >> $local ;;
        2|02) echo "<h$_size><font color='green'>$msg1</font></h$_size>" >> $local ;;
        3|03) echo "<h$_size><font color='red'>$msg1</font></h$_size>" >> $local ;;
        4|04) echo "<h$_size><font color='yellow'>$msg1</font></h$_size>" >> $local ;;
        5|05) echo "<h$_size><font color='#F535AA'>$msg1</font></h$_size>" >> $local ;;
        6|06) echo "<h$_size><font color='cyan'>$msg1</font></h$_size>" >> $local ;;
        7|07) echo "<h$_size><font color='#FF7F00'>$msg1</font></h$_size>" >> $local ;;
        8|08) echo "<h$_size><font color='#9932CD'>$msg1</font></h$_size>" >> $local ;;
        9|09) echo "<h$_size><font color='black'>$msg1</font></h$_size>" >> $local ;;
        10) echo "<h$_size>$msg1</h$_size>" >> $local ;;
        *)
            echo -e "\n\033[1;31mOpção inválida!\033[0m"
            sleep 2
            banner_menu
            ;;
    esac

    restart_services
    echo -e "\n\033[1;32mBANNER DEFINIDO!\033[0m"
    sleep 2
    banner_menu
}

# Função para remover o banner
remove_banner() {
    echo " " > $local
    echo -e "\n\033[1;32mBANNER EXCLUÍDO!\033[0m"
    restart_services
    sleep 2
    banner_menu
}

# Menu principal de gerenciamento de banners
banner_menu() {
    clear
    echo -e "\E[44;1;37m             BANNER             \E[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m1\033[1;31m]\033[1;37m • \033[1;33mADICIONAR BANNER"
    echo -e "\033[1;31m[\033[1;36m2\033[1;31m]\033[1;37m • \033[1;33mREMOVER BANNER"
    echo -e "\033[1;31m[\033[1;36m3\033[1;31m]\033[1;37m • \033[1;33mVOLTAR"
    echo ""
    echo -ne "\033[1;32mO QUE DESEJA FAZER\033[1;31m?\033[1;37m : "; read resp

    case $resp in
        1) add_banner ;;
        2) remove_banner ;;
        3) menu ;;
        *)
            echo -e "\n\033[1;31mOpção inválida!\033[0m"
            sleep 2
            banner_menu
            ;;
    esac
}

# Definir o local do banner
chk=$(grep Banner /etc/ssh/sshd_config)
[[ $(netstat -nltp | grep 'dropbear' | wc -l) != '0' ]] && {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/default/dropbear) = '0' ]] && echo 'DROPBEAR_BANNER="/etc/bannerssh"' >> /etc/default/dropbear
}
[[ "$(echo "$chk" | grep -v '#Banner' | grep Banner)" != "" ]] && {
    local=$(echo "$chk" | grep -v "#Banner" | grep Banner | awk '{print $2}')
} || {
    local="/etc/bannerssh"
    [[ $(grep -wc $local /etc/ssh/sshd_config) = '0' ]] && echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
}

# Iniciar o menu de banners
banner_menu
